# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  library-app:
    container_name: app
    image: jjhernandez99/final-isa-library
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-postgresql:5432/library
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://library-postgresql:5432/library
      - JHIPSTER_SLEEP=15 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - library-postgresql

  library-postgresql:
    container_name: app-db
    image: postgres:14.5
    # volumes:
    #   - ~/volumes/jhipster/library/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    # ports:
    #   - 5432:5432

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.10
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

  kibana:
    container_name: kibana
    image: kibana:7.17.10
    ports:
      - '5601:5601'

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.17.10
    user: root
    volumes:
      - ~/Documentos/Universidad/Final-ISA/src/main/docker/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
    # disable strict permission checks
    command: ['--strict.perms=false']

  pwa:
    container_name: pwa
    build:
      context: ~/Documentos/Universidad/final-isa-library-pwa
      dockerfile: Dockerfile
    ports:
      - 3000:3000
